#pragma config(Sensor, in8,    actuatPoten,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightLimit,     sensorTouch)
#pragma config(Sensor, dgtl2,  rightLower,     sensorTouch)
#pragma config(Sensor, dgtl11, leftLower,      sensorTouch)
#pragma config(Sensor, dgtl12, leftLimit,      sensorTouch)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rightLift,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           claw,          tmotorVex269, openLoop)
#pragma config(Motor,  port5,           actuator,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           leftLift,      tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*

    _/_/_/_/                                             _/          _/
   _/            _/    _/      _/_/_/        _/_/_/   _/_/_/_/                _/_/       _/_/_/         _/_/_/
  _/_/_/        _/    _/      _/    _/    _/           _/          _/      _/    _/     _/    _/     _/_/
 _/            _/    _/      _/    _/    _/           _/          _/      _/    _/     _/    _/         _/_/
_/              _/_/_/      _/    _/      _/_/_/       _/_/      _/        _/_/       _/    _/     _/_/_/

*/


void linearMove(int power) {
	//int power
}

void turn() {

}

vo
