#pragma config(Sensor, in8,    actuatPoten,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightLimit,     sensorTouch)
#pragma config(Sensor, dgtl2,  rightLower,     sensorTouch)
#pragma config(Sensor, dgtl11, leftLower,      sensorTouch)
#pragma config(Sensor, dgtl12, leftLimit,      sensorTouch)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightLiftFront, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightLiftBack, tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port5,           actuator,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftLiftBack,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           leftLiftFront, tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)


#include "Functions.h "


/*


    _/_/_/_/                                             _/          _/
   _/            _/    _/      _/_/_/        _/_/_/   _/_/_/_/                _/_/       _/_/_/         _/_/_/
  _/_/_/        _/    _/      _/    _/    _/           _/          _/      _/    _/     _/    _/     _/_/
 _/            _/    _/      _/    _/    _/           _/          _/      _/    _/     _/    _/         _/_/
_/              _/_/_/      _/    _/      _/_/_/       _/_/      _/        _/_/       _/    _/     _/_/_/

*/


task main() {
	linearMove(60, 1000);
}

//robot should move in linear direction with power and milliseconds
void linearMove(int power, int milliSec) {
	//motor[rightFront] = power;
  motor[rightBack]  = power;
	//motor[leftFront] = power;
	motor[leftBack] = power;
	wait1Msec(milliSec);
	resetMotors();
}
