#pragma config(Motor,  port1,           rightBack,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop)
#pragma config(Motor,  port9,           leftFront,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          leftBack,      tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) {
		motor[rightBack] = vexRT[Ch2];
		motor[rightFront] = vexRT[Ch2];
		motor[leftBack] = vexRT[Ch3];
		motor[leftFront] = vexRT[Ch3];
	}

}
